# Generated by Django 4.2.4 on 2023-08-12 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aspectapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='mallProductUrl',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='productName',
            field=models.CharField(max_length=200),
        ),
    ]
