# Generated by Django 4.2.4 on 2023-08-11 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aspectapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aspect', models.PositiveIntegerField()),
                ('gptRecommendation', models.TextField()),
                ('product1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product1_recommendations', to='aspectapp.product')),
                ('product2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product2_recommendations', to='aspectapp.product')),
            ],
        ),
    ]
