# Generated by Django 4.2.4 on 2023-08-12 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aspectapp', '0002_alter_product_mallproducturl_and_more'),
        ('comparisonapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComparisonResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aspect', models.CharField(choices=[('quality', 'Quality'), ('price', 'Price'), ('design', 'Design'), ('performance', 'Performance'), ('reviews', 'Reviews'), ('features', 'Features')], max_length=20)),
                ('recommendation', models.TextField()),
                ('product1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_as_product1', to='aspectapp.product')),
                ('product2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_as_product2', to='aspectapp.product')),
            ],
        ),
        migrations.DeleteModel(
            name='Recommendation',
        ),
    ]
