# Generated by Django 4.2.4 on 2023-08-13 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparisonapp', '0002_comparisonresult_delete_recommendation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparisonresult',
            name='aspect',
            field=models.CharField(max_length=20),
        ),
    ]
